
export const TUTORIAL_ACTION = {
    CREATE_TUTORIAL: "CREATE_TUTORIAL",
    UPDATE_TUTORIAL: "UPDATE_TUTORIAL",
    DELETE_TUTORIAL: "DELETE_TUTORIAL",
    DELETE_ALL_TUTORIALS: "DELETE_ALL_TUTORIALS",
    REFRESH_TUTORIALS: "REFRESH_TUTORIALS"
}


